### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by ehsanmostajeran** [autosportlabs/docker-sync#5]
Hi,
I am interested to use docker-sync. I have followed instruction to run it.
Unfortunately I get an error when I run it. Here is the error I get.
Traceback (most recent call last):
  File "/usr/local/bin/docker-sync", line 6, in <module>
    sync()
  File "/usr/local/lib/python2.7/dist-packages/docker_sync/cli.py", line 43, in sync
    remove_delay=parsed_args.remove_delay,
  File "/usr/local/lib/python2.7/dist-packages/docker_sync/Manager.py", line 90, in main
    containers = DOCKER.getContainers()
  File "/usr/local/lib/python2.7/dist-packages/docker_sync/lib/DockerSyncWrapper.py", line 74, in getContainers
    for cont in self.client.containers(all=True):
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 70, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 158, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 154, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client version 1.8 is too old. Minimum supported API version is 1.23, please upgrade your client to a newer version")

I appreciate if you could guide me about it.

**Comment by blalor** [comment]
You'll need to upgrade `docker-py` to work with the newer version of the Docker server.

**Comment by ehsanmostajeran** [comment]
Thanks for quick response. I upgraded docker-py to 1.8.0, and Docker server is latest version, but it still giving the same error.

**Comment by stieg** [comment]
With docker client 1.8 you highest supported API version is 1.20 (see https://docs.docker.com/engine/reference/api/docker_remote_api/).  You are obviously connecting to a docker server of version 1.11.x which supports API version 1.23, and seems to be quite strict on not supporting older versions.  You need docker client version 1.11.x

**Comment by ehsanmostajeran** [comment]
Thanks for information. It now runs perfectly, nice work. 
Let's say I create a container file as 00-hosts.yaml available as example. The first run is fine, it filters all unwanted containers. But it says "ports are different" and remove the container when I run it for the second time with exactly the same file which does not have any different port defined. Shouldn't it keep the container which is made from 00-hosts.yaml file?

**Comment by ehsanmostajeran** [comment]
Sorry my mistake, it does not remove it if same. Awesome. Thanks
